DNA = "CTAAGATTATAGTACGAGACTCTGTGGAAGAATCATGGCGTGGCAGCTGGGTGTGGATCACACGCAGTCCTCCTAATAGCTTTATCTCTTCGAAGTGAGGACTCTCCGGGTCTAGGCACGGCCCCTATAATGTTGGGTACGCGGATCAACTCCATTCAAGCGTTGGTGTATTGTACTGGTTTGTTCATACTGACTTGATGCCCACTTTTACCAAGTATTCATTTCTTATGTGCACTTAGGTAATGGGCTTGGAACGGACGGACACCTACGTATAATAACGAATCCATCTGAAGCACGTGGTATCCATTATGTATCAATTCTGAATAACTATGAGGGCGCCGTGGCCAGACCCCGCACTAAACTAATACAGTGTTGCGGATGCTACGCGGACGTTCCCACCCTCTACTTGCCCGAACACACCTGGAGTATGCGGTGCTACTTCCACGCGTCCGACCAACCAATCGTATCTTGCCCATGCGATGTAATCTAAGTGCATACTCCTGTTCAGTCTATAACGGCCCTCGAGGGTCGCTATATGAAGGGATCTTTCACCCACTCTAGAATACTTATAAACATTTGAGCAACCTGTTGGGAATCGAAATGCACGTTGCGTGCTAGGCATGATCAACGGAAGTGGATCAATGGCGACGCCGTGCGCGCACACTCAATCTTAGCAAACTTAGAACGGCGCCACGAACTCCAGCACATCTGTTTTGCTCCAAAGTTCGGGCGGACGTGACCAAGTTTGAGAGGTAAAGGTCCCATCTCAGAATAGACGTGCCAACATGAGCCCCTCTCTTCTACCGGAGCTCATACCCGGGTATGTGTCTGTCTAGCCGGAAGCCCCACCGTATGCAAACCATGAGGTACCAAGCTGCTTTGTTGGATCAGGATATGGATGTATACGACTCCGCCGAGAAGCAGAATTTCAGGAGAGGCACCTGCAC"

def REVC(DNA):
    comp_dict = {'A':'T','T':'A','C':'G','G':'C'}
    revc =''.join([comp_dict[base] for base in DNA[::-1]])
    return revc

'''rev_dna = REVC(DNA)
if rev_dna=="ACCGGGTTTT":
    print("YAY")
else:Y
    print("NAY")'''
    
Comp_DNA = REVC(DNA)
print(Comp_DNA)